.TH "bash_avpres" "1" "https://avpres.net/Bash_AVpres/" "2022-12-31" "Bash Scripts for AVpres"
.
.\" turn off justification for nroff
.if n .ad l
.\" turn off hyphenation
.nh
.
.SH NAME
bash_avpres - Installed commands provided by 'Bash AVpres'
.SH SYNOPSIS
.B bash_avpres
.SH DESCRIPTION
\fBBash AVpres\fR is a collection of Bash scripts for audio-visual preservation. One of these small programs is \fBbash_avpres\fR which lists the installed commands provided by 'Bash AVpres'.
.PP
\fBBash AVpres\fR has been tested for version 3.2 or higher. However, we strongly recommend that you use the current version 5.2.
.SH COPYRIGHT
Copyright (c) 2003-2023 by Reto Kromer
.SH LICENSE
The \fBbash_avpres\fR Bash script is released under a 3-Clause BSD License.
.SH DISCLAIMER
The \fBbash_avpres\fR Bash script is provided "as is" without warranty or support of any kind.
